version: "3.9"

services:
  vllm:
    image: lmcache/vllm-openai:latest
    command: >
      python -m vllm.entrypoints.openai.api_server
      ${MODEL_NAME}
      --tensor-parallel-size ${GPU_COUNT:-1}
      --dtype ${DTYPE:-auto}
      --kv-cache-dtype ${KV_CACHE_DTYPE:-fp16}
      --max-model-len ${MAX_MODEL_LEN:-32768}
      --gpu-memory-utilization ${GPU_UTIL:-0.85}
      --port 8000
      --host 0.0.0.0
      --enable-prefix-caching
      --kv-transfer-config '{
        "kv_connector": "LMCacheConnectorV1",
        "kv_role": "kv_both"
      }'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./models:/models
      - ./cache:/cache
      - ${WORKSPACE_HOST:-~/}:/workspace:ro
    ports:
      - "${VLLM_PORT:-8000}:8000"
    environment:
      - CUDA_VISIBLE_DEVICES=all
      - HF_HOME=/models
      - LMCACHE_CHUNK_SIZE=256
      - LMCACHE_LOCAL_CPU=true
      - LMCACHE_MAX_LOCAL_CPU_SIZE=${CPU_GB:-20}
      - LMCACHE_LOCAL_DISK=/cache/lmcache
      - LMCACHE_MAX_LOCAL_DISK_SIZE=${DISK_GB:-50}
    networks:
      - llm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  watcher:
    build:
      context: .
      dockerfile: Dockerfile.watcher
    volumes:
      - ${WORKSPACE_HOST:-~/}:/workspace:ro
      - ./scripts:/scripts:ro
    environment:
      - WATCH_DIR=${WORKSPACE_DIR:-/workspace}
      - IGNORE_FILE=.gitignore
      - VLLM_ENDPOINT=http://vllm:8000
      - WATCH_INTERVAL=${WATCH_INTERVAL:-1}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    networks:
      - llm-network
    restart: unless-stopped
    depends_on:
      - vllm

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - llm-network
    restart: unless-stopped

networks:
  llm-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config: